# Generated by Django 5.0.6 on 2024-08-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
