# Generated by Django 5.0.6 on 2024-08-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joining_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
